### PR TITLE
Add project structure

### PR DESCRIPTION
**Pull request by pakrym-stripe**
Adds projects, Github workflow to build them and an automation to release a Nuget package and update package references in readme/sample projects.

### CODE REVIEW

**Comment by pakrym-stripe** [comment]
Ah, private repos don't have actions :(

**Comment by ghost** [comment]
@pakrym-stripe I'm not opposed to making it public

**Comment by pakrym-stripe** [comment]
Let's do it. It's going to be hard without CI.

**Comment by ghost** [comment]
@pakrym-stripe ok. Done

**Pull request merged**
